#!/usr/bin/env python
import sys
import os

# reformat a file full of 16bit INTs in planar formats, eg XXXXXXXXYYYYYYYY
# to linear format XYXYXYXYXYXYXYXY

if len (sys.argv) < 4:
    print ('Usage: %s <filename> <skipbytes> <recordlength> <nplanes> <outfilename>' % os.path.basename (sys.argv[0]))
    sys.exit (0)

skip = int (sys.argv[2])
recordlength = int (sys.argv[3])
nplanes = int (sys.argv[4])
outfilename = sys.argv[5]
filename = sys.argv[1]
if '.' not in filename: # 'veh' -> 'viking.veh'
    filename = 'viking.' + filename
filename = os.path.join ('data', filename)
f = open (filename, 'rb')
f.read (skip)
content = f.read()
assert (len (content) % recordlength) == 0
planes = [content[i * recordlength: (i + 1) * recordlength] for i in range(nplanes)]
output = open (os.path.join ('data', outfilename), 'wb')
for i in range (recordlength / 2):
    for plane in range (nplanes):
        output.write (planes[plane][i * 2:(i + 1) * 2])

