#!/usr/bin/env python
#
# lasnu 'dt6' vreji ce 'attacks.bin' vreji
#
# splice dt6+attack.bin records to produce attack.full
#
# in nohrio tests dir, I use this like:
#
# ./spliceattack data/viking.dt6 data/attack.bin data/attack.full
#
#

import os

dt6_length = 80
attackbin_length = 122 # keep in sync with binsize.bin

dt6filename = sys.argv[1]
attackfilename = sys.argv[2]
finalfilename = sys.argv[3]

assert (os.path.getsize (dt6filename) % dt6_length) == 0
assert (os.path.getsize (attackfilename) % attackbin_length) == 0


nrecords = os.path.getsize (dt6filename) / dt6_length
anrecords = os.path.getsize (attackfilename) / attackbin_length
print (nrecords, anrecords)
assert nrecords == anrecords

d = open (dt6filename,'rb')
a = open (attackfilename,'rb')
out = open (finalfilename,'wb')

count = nrecords

while nrecords > 0:
    out.write(d.read (dt6_length))
    out.write(a.read (attackbin_length))
    nrecords -= 1

out.close()

print ('%d records written' % count)
